version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: preflight_dev
      POSTGRES_USER: preflight
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./apps/preflight-api
    environment:
      DATABASE_URL: postgresql://preflight:dev_password@postgres:5432/preflight_dev
      CORS_ORIGINS: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:

